In [92]:
import pandas as pd
import numpy as np

In [2]:
title = np.load('datasets/title_emb.npy')

In [3]:
len(title[0])

384

In [56]:
item = pd.read_parquet('datasets/item_used.parquet')

In [5]:
len(item['video_feature'][0])

71

In [7]:
print(type(item['video_feature'].iloc[0]))   # 타입 확인
print(repr(item['video_feature'].iloc[0]))   # raw 값 확인
print(item.head(3))

<class 'str'>
'[0.08659855 0.18466616 0.12592559 ... 0.12255595 0.43808532 0.07521491]'
   item_id                            category_name_en  \
0        0                  [Star Entertainment, star]
1        1  [wear it, fashion products, match display]
2        2                    [wear it, match display]

                        title  \
0  Stay! Robbing mobile phone
1        Add fluff for warmth
2          Warm up with fluff

                                       video_feature category_id
0  [0.08659855 0.18466616 0.12592559 ... 0.122555...      [1, 2]
1  [0.09402969 0.18858446 0.13996978 ... 0.102687...   [3, 4, 5]
2  [0.10546631 0.19659626 0.13633029 ... 0.122708...      [3, 5]

In [34]:
video = pd.read_csv('datasets/video_feature.csv')

In [46]:
video.head()

   index  item_id                                      video_feature
0      0        1  0.08659855,0.18466616,0.12592559,0.21317367,0....
1  64673        2  0.094029695,0.18858446,0.13996978,0.22282402,0...
2  75784        3  0.105466306,0.19659626,0.13633029,0.22275014,0...
3  86895        4  0.0398553,0.12616052,0.14118864,0.19212854,0.0...
4  98006        5  0.049734205,0.16419683,0.12411466,0.20954275,0...

In [47]:
video = video.sort_values('item_id')

In [50]:
video['item_id'] = video['item_id'] - 1

In [51]:
video.head()

   index  item_id                                      video_feature
0      0        0  0.08659855,0.18466616,0.12592559,0.21317367,0....
1  64673        1  0.094029695,0.18858446,0.13996978,0.22282402,0...
2  75784        2  0.105466306,0.19659626,0.13633029,0.22275014,0...
3  86895        3  0.0398553,0.12616052,0.14118864,0.19212854,0.0...
4  98006        4  0.049734205,0.16419683,0.12411466,0.20954275,0...

In [11]:
intr = pd.read_parquet('datasets/interaction.parquet')

In [54]:
valid_item_ids = intr['item_id'].unique()  # 고유값 배열 반환

video_filtered = video[video['item_id'].isin(valid_item_ids)]  # 괄호 위치 수정

In [57]:
item = item.merge(video_filtered, on='item_id', how='left')

In [67]:
item

,item_id,category_name_en,title,category_id,index,video_feature_y
0,0,"[Star Entertainment, star]",Stay! Robbing mobile phone,"[1, 2]",0,"0.08659855,0.18466616,0.12592559,0.21317367,0...."
1,1,"[wear it, fashion products, match display]",Add fluff for warmth,"[3, 4, 5]",64673,"0.094029695,0.18858446,0.13996978,0.22282402,0..."
2,2,"[wear it, match display]",Warm up with fluff,"[3, 5]",75784,"0.105466306,0.19659626,0.13633029,0.22275014,0..."
3,3,"[hairdressing, beauty]",Plant hair dye easily covers white hair,"[9, 10]",86895,"0.0398553,0.12616052,0.14118864,0.19212854,0.0..."
4,4,"[k-12, education, Academic Education]",Writing essays also has formulas.,"[12, 13, 14]",98006,"0.049734205,0.16419683,0.12411466,0.20954275,0..."
...,...,...,...,...,...,...
42796,42796,"[funny, skit]",Comedy Sketch,"[46, 173]",90004,"0.14889161,0.3347496,0.10293784,0.1914892,0.05..."
42797,42797,[military],Breaking News! US-China tensions escalate as U...,[139],90005,"0.10178868,0.19596267,0.1269141,0.21913566,0.0..."
42798,42798,"[food unboxing, gourmet, drinks, cooking]",Old debt repayment of Ma Ke box,"[435, 11, 114, 36]",90006,"0.05044358,0.144596,0.15397616,0.23870973,0.07..."
42799,42799,"[urban film, movies and TV series, films and s...",Because a sock accidentally discovered a hidde...,"[144, 44, 45, 263]",90009,"0.059333574,0.1414411,0.12682611,0.1911021,0.0..."
42800,42800,[funny],This is a master.,[46],90010,"0.09272566,0.25515822,0.14268158,0.2084568,0.0..."

In [68]:
item = item.drop(columns='index')

In [ ]:
item.to_parquet

,item_id,category_name_en,title,category_id,video_feature_y
0,0,"[Star Entertainment, star]",Stay! Robbing mobile phone,"[1, 2]","0.08659855,0.18466616,0.12592559,0.21317367,0...."
1,1,"[wear it, fashion products, match display]",Add fluff for warmth,"[3, 4, 5]","0.094029695,0.18858446,0.13996978,0.22282402,0..."
2,2,"[wear it, match display]",Warm up with fluff,"[3, 5]","0.105466306,0.19659626,0.13633029,0.22275014,0..."
3,3,"[hairdressing, beauty]",Plant hair dye easily covers white hair,"[9, 10]","0.0398553,0.12616052,0.14118864,0.19212854,0.0..."
4,4,"[k-12, education, Academic Education]",Writing essays also has formulas.,"[12, 13, 14]","0.049734205,0.16419683,0.12411466,0.20954275,0..."
...,...,...,...,...,...
42796,42796,"[funny, skit]",Comedy Sketch,"[46, 173]","0.14889161,0.3347496,0.10293784,0.1914892,0.05..."
42797,42797,[military],Breaking News! US-China tensions escalate as U...,[139],"0.10178868,0.19596267,0.1269141,0.21913566,0.0..."
42798,42798,"[food unboxing, gourmet, drinks, cooking]",Old debt repayment of Ma Ke box,"[435, 11, 114, 36]","0.05044358,0.144596,0.15397616,0.23870973,0.07..."
42799,42799,"[urban film, movies and TV series, films and s...",Because a sock accidentally discovered a hidde...,"[144, 44, 45, 263]","0.059333574,0.1414411,0.12682611,0.1911021,0.0..."
42800,42800,[funny],This is a master.,[46],"0.09272566,0.25515822,0.14268158,0.2084568,0.0..."

In [76]:
item = item.rename(columns={'video_feature_y':'video_feature'})

In [82]:
item['video_feature'] = item['video_feature'].apply(
    lambda x: list(map(float, x.split(',')))
)

In [83]:
print(type(item['video_feature'].iloc[0]))

<class 'list'>

In [84]:
item.to_parquet('datasets/item_used.parquet', index=False)

In [93]:
item = pd.read_parquet('datasets/item_used.parquet')
print(type(item['video_feature'].iloc[0]))   # list
print(len(item['video_feature'].iloc[0]))

<class 'numpy.ndarray'>
2048

In [91]:
len(item['video_feature'][0])

2048